---
Admin:
  retry_interval: 300

# List of Flow Collectors
fcs:
- ip: x.x.x.x
  username: <username>
  password: <password>
  stats_file_path: /lancope/var/sw/today/data/exporter_device_stats.txt
- ip: y.y.y.y
  username: <username>
  password: <password>
  stats_file_path: /lancope/var/sw/today/data/exporter_device_stats.txt
